#!/bin/bash
set -e
REPO=$1

if [[ -z $REPO ]]; then
    REPO=$(gum input --placeholder 'Git repository (HTTPS)')
fi

SELECTED_SPACE=$(selectw)

REPO_NAME=$(basename $REPO)
TARGET="$SELECTED_SPACE$REPO_NAME/"
gum confirm "Are you sure you want to clone $REPO to $TARGET" 
git clone $REPO $TARGET
gum confirm "Do you want to open $REPO_NAME?"
sessionp $TARGET
