#!/bin/bash
set -e
fd_path="$(get_session_ctx)"
selected_path=$(fd  . -H --base-directory $fd_path --min-depth 1 --relative-path | fzf --preview "preview_file_or_dir $fd_path/{}")
selected_path="$fd_path$selected_path"
if [[ -d "$selected_path" ]]; then
	echo "$selected_path"
elif [[ -f "$selected_path" ]]; then
	echo "$(dirname $selected_path)"
fi
